InterviewSample/Controllers/AddressesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InterviewSample.Data;
using InterviewSample.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore.Extensions.Internal;

namespace InterviewSample.Controllers
{
    [Authorize]
    public class AddressesController : Controller
    {
        private readonly ContactsContext _context;

        public AddressesController(ContactsContext context)
        {
            _context = context;    
        }

     
        public async Task<IActionResult> Index()
        {
            //var courses = _context.Contacts
            //.Include(c => c.Addresses)
            //.AsNoTracking();
            await PopulateContactsDropDownList();
            return View(await _context.Addresses.ToListAsync());
         
        }
        // GET: Addresses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var addresses = await _context.Addresses
                .SingleOrDefaultAsync(m => m.ID == id);
            if (addresses == null)
            {
                return NotFound();
            }

            return View(addresses);
        }

        private async Task<int> PopulateContactsDropDownList(object selectaddress = null)
        {
            var q =  await (from d in _context.Contacts
                    orderby d.LastName
                    select d).ToListAsync();
          //   var ls = new SelectList(q, "ID", "LastName");
             ViewBag.contactsID = new SelectList(q, "ID", "LastName");
            return 0;
        }

        private async Task<int> PopulateDropDownList(object selectaddress = null)
        {
            var q = await (from d in _context.Contacts
                           orderby d.LastName
                           select d).ToListAsync();
            //   var ls = new SelectList(q, "ID", "LastName");
            ViewBag.contactsID = new SelectList(q, "LastName", "LastName");
            return 0;
        }

        // GET: Addresses/Create
        public async Task<IActionResult> Create()
        {
            await PopulateContactsDropDownList();
            return View();
        }

        // POST: Addresses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ContactID,Name,AddressLine1,AddressLine2,City,StateCode,Zip")] Addresses addresses)
        {
            await PopulateContactsDropDownList();
            if (ModelState.IsValid)
            {
                _context.Add(addresses);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(addresses);
        }

        // GET: Addresses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var addresses = await _context.Addresses.SingleOrDefaultAsync(m => m.ID == id);
            if (addresses == null)
            {
                return NotFound();
            }
            await PopulateContactsDropDownList();
            return View(addresses);
        }

        // POST: Addresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ContactID,Name,AddressLine1,AddressLine2,City,StateCode,Zip")] Addresses addresses)
        {
            if (id != addresses.ID)
            {
                return NotFound();
            }
            await PopulateContactsDropDownList();
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(addresses);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddressesExists(addresses.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(addresses);
        }

        // GET: Addresses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var addresses = await _context.Addresses
                .SingleOrDefaultAsync(m => m.ID == id);
            if (addresses == null)
            {
                return NotFound();
            }

            return View(addresses);
        }

        // POST: Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var addresses = await _context.Addresses.SingleOrDefaultAsync(m => m.ID == id);
            _context.Addresses.Remove(addresses);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool AddressesExists(int id)
        {
            return _context.Addresses.Any(e => e.ID == id);
        }
    }
}

InterviewSample/Controllers/ContactsController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InterviewSample.Data;
using InterviewSample.Models;
using Microsoft.AspNetCore.Authorization;

namespace InterviewSample.Controllers
{
    [Authorize]
    public class ContactsController : Controller
    {
        private readonly ContactsContext _context;

        public ContactsController(ContactsContext context)
        {
            _context = context;    
        }

        // GET: Contacts
        public async Task<IActionResult> Index(string sortOrder, string currentFilter,string searchString,int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var contacts = _context.Contacts.Include(c => c.Addresses).AsNoTracking();
            //List<Contacts> cts ;

            if (!String.IsNullOrEmpty(searchString))
            {
                contacts = _context.Contacts
                      .Where(a => a.FirstName.Contains(searchString) || a.FirstName.Contains(searchString));
            }
            //else
            //{
            //     cts = await EntityFrameworkQueryableExtensions.ToListAsync((from c in _context.Contacts
            //         select c));

            //}
        //    var contacts = cts.ToAsyncEnumerable();
            switch (sortOrder)
            {
                case "name_desc":
                    contacts = contacts.OrderByDescending(s => s.LastName);
                    break;
                case "Date":
                    contacts = contacts.OrderBy(s => s.BirthDate);
                    break;
                case "date_desc":
                    contacts = contacts.OrderByDescending(s => s.BirthDate);
                    break;
                default:
                    contacts = contacts.OrderBy(s => s.LastName);
                    break;
            }

                  return View(await contacts.AsNoTracking().ToListAsync());
           
            //int pageSize = 3;
            //var z = contacts.ToEnumerable().AsQueryable();
            //return View (PaginatedList<Contacts>.Create(QueryableExtensions.AsNoTracking(z), page ?? 1, pageSize));
    }

        // GET: Contacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacts = await EntityFrameworkQueryableExtensions.SingleOrDefaultAsync(_context.Contacts, m => m.ID == id);
            if (contacts == null)
            {
                return NotFound();
            }

            //var results = context.Actions.Include("User");
            return View(contacts);
        }
        public async Task<IActionResult> SearchFirstName(string q)
        {
            var search = await EntityFrameworkQueryableExtensions.ToListAsync(_context.Contacts
                    // .Include("Addresses")
                    .Where(a => a.LastName.Contains(q)));
          //  .Take(20);
            return View(search);
        }
        public async Task<IActionResult> SearchLastName(string q)
        {
            var search = await EntityFrameworkQueryableExtensions.ToListAsync(_context.Contacts
                    // .Include("Addresses")
                    .Where(a => a.FirstName.Contains(q)));
           ;
            return View(search);
        }
        public async Task<IActionResult> ShowAllAddresses(int id)
        {
            var query = await EntityFrameworkQueryableExtensions.ToListAsync((from ct in _context.Contacts
                //join ca in _context.ContactToAddress on ct.ID equals ca.ContactId
                join a in _context.Addresses on ct.ID equals a.ContactID
                where ct.ID == id
                select a));

            return View("~/Views/Addresses/Index.cshtml", query);
        }
        public async Task<IActionResult> ShowAllPart(int id)
        {
            var query = await EntityFrameworkQueryableExtensions.ToListAsync((from ct in _context.Contacts
                //join ca in _context.ContactToAddress on ct.ID equals ca.ContactId
                join a in _context.Addresses on ct.ID equals a.ContactID
                where ct.ID == id
                      && a.Name.Contains("work")
                select a));

            return PartialView("ViewAllP", query);
        }
        // GET: Contacts/Create
        public IActionResult Create()
        {
            PopulateAddressDropDownList();
            return View();
        }

        // POST: Contacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FirstName,LastName,EmailAddress,BirthDate,NumberOfComputers")] Contacts contacts)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contacts);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            PopulateAddressDropDownList();
            return View(contacts);
        }

        // GET: Contacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacts = await _context.Contacts.SingleAsync(m => m.ID == id);
            if (contacts == null)
            {
                return NotFound();
            }
            return View(contacts);
        }
        public async Task<IActionResult> EditPart(int id)
        {
            var query =  await EntityFrameworkQueryableExtensions.FirstOrDefaultAsync((from ct in _context.Contacts
                //join ca in _context.ContactToAddress on ct.ID equals ca.ContactId
                join a in _context.Addresses on ct.ID equals a.ContactID
                where ct.ID == id  && a.Name.Contains("Home")
                select a));
            
            //   return View("EditPart", contacts);
            return PartialView("TestView", query);
        }
        private void PopulateAddressDropDownList(object selectaddress = null)
        {
            var q = from d in _context.Addresses
                                   orderby d.Name
                                   select d;
            var ls = new SelectList(q.AsNoTracking(), "ID", "Name");
            ViewBag.AddressID = ls;//new SelectList(q.AsNoTracking(), "AddressID", "Name", selectaddress);
        }
       
        // POST: Contacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FirstName,LastName,EmailAddress,BirthDate,NumberOfComputers")] Contacts contacts)
        {
            if (id != contacts.ID)
            {
                return NotFound();
            }
        //    var cont = await _context.Contacts.SingleAsync(c => c.ID == id);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contacts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContactsExists(contacts.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException /* ex */)
                {
                    //Log the error (uncomment ex variable name and write a log.)
                    ModelState.AddModelError("", "Unable to save changes. " +
                        "Try again, and if the problem persists, " +
                        "see your system administrator.");
                }
                //var query = await (from ct in _context.Contacts//join ca in _context.ContactToAddress on ct.ID equals ca.ContactId
                //                   join a in _context.Addresses on ct.ID equals a.ContactID
                //                   where ct.ID == id
                //                   select a).ToListAsync();
                //PopulateAddressDropDownList(query);
                return RedirectToAction("Index");
            }
            return View(contacts);
        }

        // GET: Contacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contacts = await EntityFrameworkQueryableExtensions.SingleOrDefaultAsync(_context.Contacts, m => m.ID == id);
            if (contacts == null)
            {
                return NotFound();
            }

            return View(contacts);
        }

        // POST: Contacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contacts = await EntityFrameworkQueryableExtensions.SingleOrDefaultAsync(_context.Contacts, m => m.ID == id);

InterviewSample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InterviewSample.Data;
using InterviewSample.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InterviewSample.Controllers
{
    public class HomeController : Controller
    {
        private readonly ContactsContext _context;

        public HomeController(ContactsContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> ComputerStatistics()
        {
            var data =
                _context.Contacts.GroupBy(k => k.NumberOfComputers)
                    .Select(ko => new StatisticsViewModel {ComputersCount = ko.Key, ContactsCount = ko.Count()});

            return View(await data.AsNoTracking().ToListAsync()); ;
        }

        public async Task<ActionResult> AddressStats()
        {
            var data = from ct in _context.Contacts
                       join a in _context.Addresses on ct.ID equals a.ContactID
                       // where ct.ID == 1
                       group a by a.Name into aName
                       select new StatisticsViewModel
                       {
                           Name = aName.Key,
                           AddressCount = aName.Count()
                       };

            return View(await data.AsNoTracking().ToListAsync()); ;
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

InterviewSample/Views/Home/AddressStats.cshtml
@model IEnumerable<InterviewSample.Models.StatisticsViewModel>

    @{
        ViewData["Title"] = "Address Statistics";
    }
<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h2>Address Statistics</h2>
    </div>
   
            <table>
                <tr>
                    <th class="text-center">
                        Address
                    </th>
                    <th  class="text-center">
                         Number of contacts
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="text-center">
                            @item.AddressCount
                        </td>
                    </tr>
                }
            </table>
        </div>

InterviewSample/Views/Home/ComputerStatistics.cshtml
@model IEnumerable<InterviewSample.Models.StatisticsViewModel>

    @{
        ViewData["Title"] = "Computer Statistics";
    }

<div>ViewData["Title"]</div> 
<p></p>
<div class='panel panel-primary'>
        <div class='panel-heading'>
            <h2>Computer Statistics</h2>
        </div>

        <table>
            <tr>
                <th>
                    contacts # 
                </th>
                <th>
                     Rigs
                </th>
            </tr>

            @foreach (var item in Model)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContactsCount)
                    </td>
                    <td>
                        @item.ComputersCount
                    </td>
                </tr>
                }
        </table>
    </div>

InterviewSample/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/a3.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Managing Contacts
                    <a class="btn btn-default" asp-area="" asp-controller="Contacts" asp-action="Index">Show All Contacts</a>

                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/a3.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                     Managing Addresses
                    <a class="btn btn-default" h<a asp-area="" asp-controller="Addresses" asp-action="Index">Show All Addresses</a>
                  
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/a3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                   Call group by to show Number of addresses belonging to contact
                    <a class="btn btn-default" asp-area="" asp-controller="Home" asp-action="AddressStats">Show Address Statistics
                       
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/a3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Call group by to show Number of computers at contact
                    <a class="btn btn-default"  asp-area="" asp-controller="Home" asp-action="ComputerStatistics">Show Computer Statisticss
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="jumbotron">
    <h1>Contact Management</h1>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Welcome to Sample of Contact Management</h2>
        <p>
          This app is using Entity Framework for an
            ASP.NET Core MVC web application.
        </p>
    </div>
    
    <div class="col-md-4">
        <h2>Download it</h2>
        <p>You can download the completed project from GitHub.</p>
        <p><a class="btn btn-default" href="https://github.com/pgavril/IntSample.git">See project source code &raquo;</a></p>
    </div>
</div>